### PR TITLE
updated to use Intouch/NewRelic features

### PR DESCRIPTION
**Pull request by stikmanw**
Removed a lot of code that does not work at runtime.  NewRelic does not support setting ini settings at runtime per their new PHP Agent.  If you are not interested in supporting repo, I am happy to take over let me know.  I am building this into our core api framework at our company.

### CODE REVIEW

**Comment by stikmanw** [comment]
I also suggest you move this to version release like 1.0.0 or something since it has potentially breaking changes (missing methods and pimple identifiers.)

**Comment by mcuadros** [comment]
Hi @stikmanw 

I am not user of NewRelic anymore, even of PHP. So if you are interested I can transfer you the ownership of this repository.

**Comment by colinodell** [comment]
+1

**Comment by stikmanw** [comment]
I would take ownership of it if you are willing to transfer.  I will be supporting it as part of our companies internal platform.

**Comment by mcuadros** [comment]
@stikmanw "stikmanw/silex-newrelic already exists"

**Comment by stikmanw** [comment]
I renamed my local version as I have some private repos looking at it at the moment for testing other things.  You can transfer now and I will do the merge / versioning.

**Comment by mcuadros** [comment]
@stikmanw "stikmanw already has a repository in the mcuadros/silex-newrelic network
 Unwatch "

**Comment by stikmanw** [comment]
unwatched and deleted

**Comment by mcuadros** [comment]
done

**Comment by stikmanw** [comment]
Can you retransfer...hit one of my exchange filter rules.

**Comment by mcuadros** [comment]
done

**Pull request merged**
